# Generated by Django 6.0.7 on 2026-08-02 17:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant investi')),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant deja rembourse')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('REFUNDED', 'Rembourse'), ('PARTIALLY_REFUNDED', 'Partiellement rembourse')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investors.investorprofile', verbose_name='Profil investisseur')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='projects.project', verbose_name='Projet')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investment', to='transactions.transaction', verbose_name="Transaction d'origine")),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['investor_profile', '-created_at'], name='investments_investo_42c462_idx'), models.Index(fields=['project', '-created_at'], name='investments_project_2ef9f8_idx')],
            },
        ),
    ]
