# Generated by Django 6.0.7 on 2026-08-24 07:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        ('investors', '0001_initial'),
        ('projects', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_investo_42c462_idx',
        ),
        migrations.RemoveIndex(
            model_name='investment',
            name='investments_project_2ef9f8_idx',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investorprofile'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('REFUNDED', 'Remboursé'), ('PARTIALLY_REFUNDED', 'Partiellement remboursé')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='transactions.transaction'),
        ),
    ]
