# Generated by Django 6.0.7 on 2026-08-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrateur'), ('USERADMIN', 'Administrateur'), ('ENTREPRISE', 'Entreprise'), ('INVESTISSEUR', 'Investisseur'), ('PLATFORM', 'Compte Plateforme')], default='INVESTISSEUR', max_length=20, verbose_name='Rôle'),
        ),
    ]
