# Generated by Django 6.0.7 on 2026-08-01 21:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'enregistrement légal")),
                ('company_type', models.CharField(blank=True, help_text='Ex: SARL, SAS, SA...', max_length=100, verbose_name='Forme juridique')),
                ('industry_sector', models.CharField(blank=True, max_length=100, verbose_name="Secteur d'activité")),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('legal_representative_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du représentant légal')),
                ('legal_representative_position', models.CharField(blank=True, max_length=100, verbose_name='Fonction du représentant légal')),
                ('legal_representative_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du représentant légal')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('iban', models.CharField(blank=True, max_length=34, validators=[django.core.validators.RegexValidator(message='Format IBAN invalide.', regex='^[A-Z]{2}[0-9]{2}[A-Z0-9]{11,30}$')], verbose_name='IBAN')),
                ('bic_swift', models.CharField(blank=True, max_length=11, verbose_name='Code BIC/SWIFT')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Nom de la banque')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name="Logo de l'entreprise")),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='companies/documents/registration/', verbose_name="Extrait d'immatriculation (Kbis ou équivalent)")),
                ('legal_representative_id_document', models.FileField(blank=True, null=True, upload_to='companies/documents/representative_id/', verbose_name="Pièce d'identité du représentant légal")),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente de vérification'), ('APPROVED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut de vérification')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Entreprise',
                'verbose_name_plural': 'Profils Entreprises',
                'ordering': ['-created_at'],
            },
        ),
    ]
