# Generated by Django 6.0.7 on 2026-08-02 23:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name="Taux d'interet annuel (%)")),
                ('number_of_installments', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name="Nombre d'echeances")),
                ('frequency_days', models.PositiveIntegerField(default=30, verbose_name='Frequence entre echeances (jours)')),
                ('total_capital', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Capital total a rembourser')),
                ('total_interest', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total des interets')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Termine'), ('DEFAULTED', 'En defaut')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_plan', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Plan de remboursement',
                'verbose_name_plural': 'Plans de remboursement',
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name="Numero d'echeance")),
                ('due_date', models.DateField(verbose_name="Date d'exigibilite")),
                ('capital_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Part de capital')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Part d'interets")),
                ('status', models.CharField(choices=[('SCHEDULED', 'Planifiee'), ('PAID', 'Payee'), ('LATE', 'En retard'), ('CANCELLED', 'Annulee')], default='SCHEDULED', max_length=20, verbose_name='Statut')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement effectif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='investments.investment', verbose_name='Investissement concerne')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='repayments.repaymentplan', verbose_name='Plan de remboursement')),
            ],
            options={
                'verbose_name': 'Echeance de remboursement',
                'verbose_name_plural': 'Echeances de remboursement',
                'ordering': ['due_date', 'installment_number'],
                'indexes': [models.Index(fields=['investment', 'installment_number'], name='repayments__investm_e2e7ba_idx'), models.Index(fields=['status', 'due_date'], name='repayments__status_ab3845_idx')],
            },
        ),
    ]
