# Generated by Django 6.0.7 on 2026-08-18 23:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        ('projects', '0001_initial'),
        ('repayments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repayment',
            options={'ordering': ['due_date'], 'verbose_name': 'Échéance', 'verbose_name_plural': 'Échéances'},
        ),
        migrations.RemoveIndex(
            model_name='repayment',
            name='repayments__investm_e2e7ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='repayment',
            name='repayments__status_ab3845_idx',
        ),
        migrations.AlterField(
            model_name='repayment',
            name='capital_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='installment_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='investments.investment'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='repayments.repaymentplan'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Planifiée'), ('PAID', 'Payée'), ('LATE', 'En retard'), ('CANCELLED', 'Annulée')], default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='frequency_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text="Taux d'intérêt annuel (%)", max_digits=5),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='number_of_installments',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_plan', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('COMPLETED', 'Terminé'), ('DEFAULTED', 'En défaut')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='total_capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='repaymentplan',
            name='total_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='updated_at',
        ),
    ]
