# Generated by Django 6.0.7 on 2026-08-02 07:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Reference')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Depot'), ('WITHDRAWAL', 'Retrait'), ('INVESTMENT', 'Investissement'), ('REFUND', 'Remboursement'), ('INTEREST', 'Interet'), ('COMMISSION', 'Commission')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminee'), ('FAILED', 'Echouee'), ('CANCELLED', 'Annulee')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name="Raison de l'echec")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='projects.project', verbose_name='Projet concerne')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='transaction_wallet__dbc2ee_idx')],
            },
        ),
    ]
