# Generated by Django 6.0.7 on 2026-08-25 13:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('transactions', '0001_initial'),
        ('wallets', '0002_alter_wallet_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant net (après frais)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallets.wallet', verbose_name='Portefeuille destination'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence externe'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Frais'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux de frais (%)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='wallets.wallet', verbose_name='Portefeuille source'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échouée'), ('CANCELLED', 'Annulée'), ('REVERSED', 'Inversée')], default='PENDING', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('INVESTMENT', 'Investissement'), ('REFUND', 'Remboursement'), ('INTEREST', 'Intérêt'), ('COMMISSION', 'Commission'), ('TRANSFER', 'Transfert'), ('FEE', 'Frais'), ('REBATE', 'Ristourne')], max_length=20, verbose_name='Type de transaction'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['source_wallet', '-created_at'], name='transaction_source__f27efa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['destination_wallet', '-created_at'], name='transaction_destina_c282c7_idx'),
        ),
    ]
