# Generated by Django 6.0.7 on 2026-08-02 07:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde total')),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Solde bloqué')),
                ('currency', models.CharField(default='EUR', help_text="Code ISO 4217 (EUR, USD...). Une seule devise gérée pour l'instant.", max_length=3, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CREDIT', 'Crédit'), ('DEBIT', 'Débit'), ('LOCK', 'Blocage de fonds'), ('UNLOCK', 'Déblocage de fonds')], max_length=10, verbose_name='Type de mouvement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant du mouvement')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Solde après mouvement')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wallets.wallet', verbose_name='Portefeuille')),
            ],
            options={
                'verbose_name': 'Historique de portefeuille',
                'verbose_name_plural': 'Historiques de portefeuille',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__gte', 0)), name='wallet_locked_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('locked_balance__lte', models.F('balance'))), name='wallet_locked_balance_lte_balance'),
        ),
    ]
