# Generated by Django 6.0.7 on 2026-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='XOF', help_text="Code ISO 4217 (EUR, USD...). Une seule devise gérée pour l'instant.", max_length=3, verbose_name='Devise'),
        ),
    ]
