# Generated by Django 6.0.7 on 2026-08-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('nationality', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone')),
                ('address_line', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='investors/photos/', verbose_name='Photo de profil')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='investors/documents/identity/', verbose_name="Pièce d'identité")),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='investors/documents/address/', verbose_name='Justificatif de domicile')),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente de vérification'), ('APPROVED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut de vérification')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Investisseur',
                'verbose_name_plural': 'Profils Investisseurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
