# Generated by Django 6.0.7 on 2026-08-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ACCOUNT_ACTIVATED', 'Compte active'), ('KYC_APPROVED', 'KYC approuve'), ('KYC_REJECTED', 'KYC rejete'), ('KYB_APPROVED', 'KYB approuve'), ('KYB_REJECTED', 'KYB rejete'), ('PROJECT_SUBMITTED', 'Projet soumis'), ('PROJECT_APPROVED', 'Projet approuve'), ('PROJECT_REJECTED', 'Projet refuse'), ('PROJECT_NEEDS_CORRECTION', 'Corrections demandees'), ('INVESTMENT_RECEIVED', 'Investissement recu'), ('REPAYMENT_PAID', 'Echeance payee')], max_length=30, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
